require_relative './stack_item'
require_relative './bool_class'
require_relative './number_classes'
require_relative './decimal_class'
require_relative './closure_class'
require_relative './message_class'
require_relative './bundle_class'
require_relative './duck_interpreter'
